name: Deploy Multiple Docker fibonacci
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Service Key
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-398820

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker  

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-k8s-cluster
          location: us-west1-a

      - name: Builds
        run: |-
          docker build -t aarjavdixit1/multi-client:latest -t aarjavdixit1/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t aarjavdixit1/multi-server:latest -t aarjavdixit1/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t aarjavdixit1/multi-worker:latest -t aarjavdixit1/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push aarjavdixit1/multi-client:latest
          docker push aarjavdixit1/multi-server:latest
          docker push aarjavdixit1/multi-worker:latest
          
          docker push aarjavdixit1/multi-client:${{ env.SHA }}
          docker push aarjavdixit1/multi-server:${{ env.SHA }}
          docker push aarjavdixit1/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=multi-server:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=aarjavdixit1/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=cygnetops/multi-worker:${{ env.SHA }}

