name: Deploy Multiple Docker fibonacci
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t aarjavdixit1/multi-client:v4 ./client
      - run: docker build -t aarjavdixit1/multi-nginx ./nginx
      - run: docker build -t aarjavdixit1/multi-server ./server
      - run: docker build -t aarjavdixit1/multi-worker ./worker

      - run: docker push aarjavdixit1/multi-client:v4
      - run: docker push aarjavdixit1/multi-nginx
      - run: docker push aarjavdixit1/multi-server
      - run: docker push aarjavdixit1/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: multi-docker
#          environment_name: Multi-docker-env
#          existing_bucket_name: elasticbeanstalk-us-east-1-553617938426
#          region: us-east-1
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip